from ..direction import Direction

DIRECTIONS = [Direction.NORTH, Direction.SOUTH, Direction.EAST, Direction.WEST]
REGIONS_WALL_INDEX = -1

# Temple
BUILD_ROOM_ATTEMPTS = 500

# Room
ROOM_MAX_SIZE = 11
ROOM_MIN_SIZE = 5

# Corridor
WINDING_PROBABILITY = 0.4

# Connection
ACCEPTABLE_DISTANCE = 2
PROBABILITY_ADD_RANDOM_JUNCTION = 0.03
