from ..core.colors import Color


class Icon:
    GATEWAY = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.BLOOD_RED_TEXT} 𝛑 {Color.RESET}"
    LEVEL_ENTRANCE = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.DARK_SPRING_GREEN_TEXT} I {Color.RESET}"
    LEVEL_EXIT = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.DARK_SPRING_GREEN_TEXT} O {Color.RESET}"

    ROOM_FLOOR = f"{Color.BLOOD_RED_BACKGROUND}{Color.WHITE_TEXT} · {Color.RESET}"
    CORRIDOR_FLOOR = f"{Color.DARK_VANILLA_BACKGROUND}{Color.BLOOD_RED_TEXT} · {Color.RESET}"
    DOOR = f"{Color.NATURAL_WOOD_BROWN_BACKGROUND}{Color.NATURAL_WOOD_BROWN_TEXT} * {Color.RESET}"
    WALL = f"{Color.BLACK_MAGIC_BACKGROUND}{Color.CITRON_TEXT} ✕ {Color.RESET}"
    STAIRS = f"{Color.DARK_VANILLA_BACKGROUND}{Color.BLOOD_RED_TEXT} < {Color.RESET}"

    GROUND = f"{Color.BLACK_MAGIC_BACKGROUND}{Color.CITRON_TEXT} · {Color.RESET}"
    TREE = f"{Color.BILBAO_BACKGROUND}{Color.MYRTLE_TEXT} ψ {Color.RESET}"
    STONE = f"{Color.BLACK_MAGIC_BACKGROUND}{Color.SPANISH_GRAY_TEXT} ○ {Color.RESET}"
    WATER = f"{Color.MONTE_CARLO_BACKGROUND}{Color.VIRIDIAN_TEXT} ~ {Color.RESET}"
    SWAMP = f"{Color.RANGOON_GREEN_BACKGROUND}{Color.WEDGEWOOD_TEXT} ~ {Color.RESET}"

    QUEST_DOOR = f"{Color.HARVEST_GOLD_BACKGROUND}{Color.HARVEST_GOLD_TEXT} * {Color.RESET}"
    CHEST = f"{Color.BLOOD_RED_BACKGROUND} ❒ {Color.RESET}"
    INFORMATION_BOARD = f"{Color.BLOOD_RED_BACKGROUND}{Color.CORNFLOWER_BLUE_TEXT} ⚠ {Color.RESET}"

    CORPSE = f"{Color.BLOOD_RED_TEXT} ☠ {Color.RESET}"
