from ..core.colors import Color


class Icon:
    GATEWAY_ENTRANCE = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.BLOOD_RED_TEXT} П {Color.RESET}"
    GATEWAY_EXIT = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.BURGUNDY_TEXT} П {Color.RESET}"
    GRATE = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.BLOOD_RED_TEXT} ♯ {Color.RESET}"
    LEVEL_ENTRANCE = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.BLOOD_RED_TEXT} 🡠 {Color.RESET}"
    LEVEL_EXIT  = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.BURGUNDY_TEXT} 🡢 {Color.RESET}"
    CLOSED_LEVEL_EXIT = f"{Color.DARK_SPRING_GREEN_BACKGROUND}{Color.BLOOD_RED_TEXT} ♅ {Color.RESET}"

    ROOM_FLOOR = f"{Color.BLOOD_RED_BACKGROUND}{Color.WHITE_TEXT} · {Color.RESET}"
    CORRIDOR_FLOOR = f"{Color.DARK_VANILLA_BACKGROUND}{Color.BLOOD_RED_TEXT} · {Color.RESET}"
    DOOR = f"{Color.DARK_VANILLA_BACKGROUND}{Color.NATURAL_WOOD_BROWN_TEXT} П {Color.RESET}"
    WALL = f"{Color.BLACK_MAGIC_BACKGROUND}{Color.CITRON_TEXT} ✕ {Color.RESET}"
    STAIRS = f"{Color.DARK_VANILLA_BACKGROUND}{Color.BLOOD_RED_TEXT} < {Color.RESET}"
    QUEST_DOOR = f"{Color.DARK_VANILLA_BACKGROUND}{Color.BLOOD_RED_TEXT} П {Color.RESET}"

    GROUND = f"{Color.BLACK_MAGIC_BACKGROUND}{Color.CITRON_TEXT} · {Color.RESET}"
    TREE = f"{Color.BILBAO_BACKGROUND}{Color.MYRTLE_TEXT} ψ {Color.RESET}"
    STONE = f"{Color.BLACK_MAGIC_BACKGROUND}{Color.SPANISH_GRAY_TEXT} ○ {Color.RESET}"
    WATER = f"{Color.MONTE_CARLO_BACKGROUND}{Color.VIRIDIAN_TEXT} ~ {Color.RESET}"
    SWAMP = f"{Color.RANGOON_GREEN_BACKGROUND}{Color.WEDGEWOOD_TEXT} ~ {Color.RESET}"

    INFORMATION_BOARD = f"{Color.BLOOD_RED_BACKGROUND}{Color.CORNFLOWER_BLUE_TEXT} ⚠ {Color.RESET}"

    CORPSE = f"{Color.WHITE_TEXT} ☠ {Color.RESET}"

    EMPTY_SLOT = f"x"
